[project]
name = "two-link-robot-simulation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mardhav-2008", email = "mardhavrayapati81@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "plotly>=7.1.0",
    "pygame-ce>=2.5.8",
]

[project.scripts]
two-link-robot-simulation = "two_link_robot_simulation:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
